#!/bin/bash
sudo apt-get update && sudo apt-get upgrade -y

sudo apt-get install -y git mc docker.io

source /etc/bash_completion.d/docker.io
sudo docker -d &
sudo docker run --name postgres-database -p 0.0.0.0:5432:5432 -e POSTGRES_PASSWORD=123456 -d postgres:9.3.5
