#!/bin/bash
path=$(pwd)
sudo sh -c "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"

sudo apt-get update && sudo apt-get upgrade -y

sudo apt-get install -y git mc ssh 

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
sudo sh -c "echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
sudo apt-get update
sudo apt-get install lxc-docker -y
 
sudo sh -c "curl -L https://github.com/docker/fig/releases/download/1.0.0/fig-`uname -s`-`uname -m` > /usr/local/bin/fig"
sudo chmod +x /usr/local/bin/fig
 
cd /tmp
git clone https://gist.github.com/76b450a0c986e576e98b.git
cd 76b450a0c986e576e98b
sudo mv docker-cleanup /usr/local/bin/docker-cleanup
sudo chmod +x /usr/local/bin/docker-cleanup

cd $path
sudo fig up

#sudo docker run  -p 0.0.0.0:5432:5432 -e POSTGRES_PASSWORD=123456 -d postgres:9.3.5
#sudo docker run  -p 0.0.0.0:61616:61616  -d aterreno/activemq-dockerfile
#sudo docker run  -p 0.0.0.0:18082:18082 -p 0.0.0.0:8080:8080 -v=/home/alex/ya-git/yandexer.properties:/home/camelot-yandexeyandexer.properties  -d mylnikovorg/ya-image /bin/sh -c "cd /home/camelot-yandexer && mvn clean compile  camelot-test:run"
#sudo docker run --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8081:8080 --detach=true --name=cadvisor google/cadvisor:latest

