#!/bin/bash
sudo apt-get update && sudo apt-get upgrade -y

sudo apt-get install -y git mc ssh docker.io

source /etc/bash_completion.d/docker.io
#sudo docker -d &
sudo docker run --name postgres-database -p 0.0.0.0:5432:5432 -e POSTGRES_PASSWORD=123456 -d postgres:9.3.5
sudo docker run --name activemq -p 0.0.0.0:61616:61616  -d kdomanski/activemq
sudo docker run --name web -p 0.0.0.0:18082:18082 -p 0.0.0.0:8080:8080  -d mylnikovorg/ya-image
sudo docker run --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8081:8080 --detach=true --name=cadvisor google/cadvisor:latest
